### ISSUE TITLE
Signing into CLI refers to powershell

### ISSUE THREAD

**Issue by ddyett** [microsoftgraph/msgraph-cli#123]
They're probably using the same id resulting in this.

![image](https://user-images.githubusercontent.com/20829981/167488115-e962baaa-ca68-4d0d-80ce-29f3031ae2cc.png)

**Comment by calebkiage** [comment]
We decided to use the same client id as PowerShell a few sprints back. See #80

**Comment by darrelmiller** [comment]
I suggest that we change the app registration to just say Microsoft Graph Command Line Tools.  /cc @maisarissi

**Comment by maisarissi** [comment]
Agreed! Just raised the issue for trach the change: https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1481
