### ISSUE TITLE
Support more auth strategies than device code

### ISSUE THREAD

**Issue by ddyett** [microsoftgraph/msgraph-cli#125]
mgc login -h shows only one auth strategy available at the moment.

Options:
  --scopes <scopes> (REQUIRED)  The login scopes e.g. User.Read
  --client-id <client-id>       The client id
  --tenant-id <tenant-id>       The tenant id
  --strategy <DeviceCode>       The authentication strategy to use. [default: DeviceCode]
  -?, -h, --help                Show help and usage information

**Comment by calebkiage** [comment]
Tasks:
- [x] #146
- [x] #147

**Comment by calebkiage** [comment]
Additional tasks:

- [ ] #161
- [ ] #162
- [ ] #163

**Comment by baywet** [comment]
since this is already broken down to other issues, closing this one for clarity
