### ISSUE TITLE
%24 and $ used in URL when using --select and/or --top options

### ISSUE THREAD

**Issue by tclev** [microsoftgraph/msgraph-cli#133]
I was trying to use --select and --top but it didn't seem to be working. I think used Fiddler to look at what was being sent and it was creating URLs like this: 
```https://graph.microsoft.com/v1.0/users?%24$top=5&%24$select=id```
Using one or the other is fine, but both cause the option to be ignored.

**Comment by calebkiage** [comment]
Hey @tclev, thanks for raising an issue.
To help speed up troubleshooting, please provide us with information on:

1. The CLI version you're running
2. The command you're running
3. The platform e.g., Windows, Linux, Docker

**Comment by tclev** [comment]
Sure! Sorry I didn't post it earlier.

Version:
```
mgc.exe --version
0.1.0-preview.4
```

Command:
```
mgc.exe users list --top 5 --select "id"
```

Platform: Windows 10

**Comment by calebkiage** [comment]
Hello @tclev, this specific error should have been fixed in the latest nightly (available on docker or manual build). It should work fine on the next release. If you would like to try it out early, you can try the docker nightly image (`docker pull ghcr.io/microsoftgraph/msgraph-cli:nightly`).

**Comment by calebkiage** [comment]
The [new release](https://github.com/microsoftgraph/msgraph-cli/releases/tag/v0.1.0-preview.5) is up and should fix this problem. Feel free to reopen this issue in case you face any challenges.
