### ISSUE TITLE
Build failure: Unable to find package Microsoft.Graph.Cli.Core.

### ISSUE THREAD

**Issue by xianw-msft** [microsoftgraph/msgraph-cli#144]
Hi, people.

I was trying to build this locally, but it seems Microsoft.Graph.Cli.Core is required. Where can I get this?

Thanks.
Xiang Wu

PS C:\Users\xianw.FAREAST\source\repos\msgraph-cli> dotnet build
Microsoft (R) Build Engine version 17.2.0+41abc5629 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
C:\Users\xianw.FAREAST\source\repos\msgraph-cli\src\msgraph-cli.csproj : error NU1101: Unable to find package Microsoft.Graph.Cli.Core. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org [C
:\Users\xianw.FAREAST\source\repos\msgraph-cli\msgraph-cli.sln]
C:\Users\xianw.FAREAST\source\repos\msgraph-cli\src\msgraph-cli.csproj : error NU1101: Unable to find package Microsoft.Kiota.Cli.Commons. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
 [C:\Users\xianw.FAREAST\source\repos\msgraph-cli\msgraph-cli.sln]
  Failed to restore C:\Users\xianw.FAREAST\source\repos\msgraph-cli\src\msgraph-cli.csproj (in 1.71 sec).

Build FAILED.

C:\Users\xianw.FAREAST\source\repos\msgraph-cli\src\msgraph-cli.csproj : error NU1101: Unable to find package Microsoft.Graph.Cli.Core. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org [C
:\Users\xianw.FAREAST\source\repos\msgraph-cli\msgraph-cli.sln]
C:\Users\xianw.FAREAST\source\repos\msgraph-cli\src\msgraph-cli.csproj : error NU1101: Unable to find package Microsoft.Kiota.Cli.Commons. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
 [C:\Users\xianw.FAREAST\source\repos\msgraph-cli\msgraph-cli.sln]
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:04.04
PS C:\Users\xianw.FAREAST\source\repos\msgraph-cli>

**Comment by calebkiage** [comment]
That package is published to a github packages NuGet repository. To get access to it locally, you will need to create a personal access token with package read access and authorize it for the `microsoft` organization. After you have that, you should create or update your nuget.config file as shown below:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
        <clear />
        <add key="microsoft-gh" value="https://nuget.pkg.github.com/microsoft/index.json" />
        <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
    </packageSources>
    <packageSourceCredentials>
        <microsoft-gh>
            <add key="Username" value="<username>" />
            <add key="ClearTextPassword" value="<access_token>" />
        </microsoft-gh>
    </packageSourceCredentials>
</configuration>
```

**Comment by danieldjewell** [comment]
As a polite observation, it would be far better to include this dependency as a git submodule or otherwise.

From a software development / CI / reproducibility standpoint, it's really ideal to be able to clone the repository and build the project with a handful of straightforward commands... In my case, I saw a `.sln` file ... so out came `dotnet build`... And then this error. Haven't tried it in VS2022 yet but ... seems like that would be broken too? 

At a minimum, I would suggest putting this information in the main README (or perhaps a `BUILDING.md` or other development caveats reference in the root of the repository...)

**Comment by calebkiage** [comment]
Hey @danieldjewell, thanks for the suggestion. We'll add building instructions to the repository soon.

**Comment by calebkiage** [comment]
Microsoft.Graph.Cli.Core is on NuGet
