### ISSUE TITLE
Unverified publisher when trying to log-in

### ISSUE THREAD

**Issue by Fuco1** [microsoftgraph/msgraph-cli#155]
This does not inspire confidence especially from "official" microsoft application. 

![image](https://user-images.githubusercontent.com/2664959/185645316-3a391b48-6362-40f2-862a-47df79a0d7a8.png)

**Comment by darrelmiller** [comment]
This is an unfortunate situation that we are working to rectify.  However, currently Microsoft teams that build applications that require user consent cannot participate in the "Verified Publisher" program.
