### ISSUE TITLE
Support client secret login

### ISSUE THREAD

**Issue by calebkiage** [microsoftgraph/msgraph-cli#161]

**Comment by calebkiage** [comment]
Since the client secret is essentially a password, how should we store this information so as not to ask for it again on each command run? The login command is essentially a different application invocation from any other command run which means we need to have the secret accessible for token acquisition.

We can set environment variables using the [Environment.SetEnvironmentVariable](https://learn.microsoft.com/en-us/dotnet/api/system.environment.setenvironmentvariable) function of .NET but on Linux, it only supports setting the Process environment block.

We can also have the user set the environment variables in advance, but UX suffers for users who don't know this mechanism.

We could also ask for the secret on every run, but this impacts unattended flows.

cc @darrelmiller, @ddyett, @baywet, @CarolKigoonya

**Comment by baywet** [comment]
shell variable?

**Comment by calebkiage** [comment]
@baywet, I'd thought about using the [Process](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process?view=net-7.0) class to create shell variables from within a C# program but it doesn't work since setting a variable is done by the shell and not an external program. I tried setting the process file name to the shell itself (pwsh.exe) then setting the arguments to a variable declaration but the variable remains unset.

**Comment by baywet** [comment]
ah because it spawns a sub-process instead of running in the parent shell instance. I hadn't thought about that, but it now sounds obvious.
Jus to recap things, we need the secret to get a token. And I think I remember you saying that the tokens are not being cached by Azure identity/MSAL in case of client credentials, correct?
Do we have any insight in why it's not being cached? any rationale the identity team is providing?

**Comment by calebkiage** [comment]
@baywet, it's possible to cache the token for client secret credential by setting the token persistence options. I think I said PowerShell SDK doesn't cache tokens for client secret and client certificate credentials.

**Comment by baywet** [comment]
Thanks for the clarification here. Just to recap the call we just had: we should reach out to Azure identity to understand whether the secret parameter requirement to re-hydrate the token cache is a security requirement or whether it's an oversight for our scenario.
In the case of the former, we'll need to find a solution to work around the issue, in the case of the later, maybe they can accommodate us.

**Comment by baywet** [comment]
link to the issue created in Azure identity https://github.com/Azure/azure-sdk-for-net/issues/31499

**Comment by darrelmiller** [comment]
> We could also ask for the secret on every run, but this impacts unattended flows.
Users who write scripts can pass in an environment variable.

We cannot cache secrets.  If we can cache the token generated from the client credentials then that is fine. But we cannot cache the secret itself.

Update:  Following a conversation with Carol, I now have a better understanding of the problem.  Can we get a better understanding of how Az CLI solves this?

**Comment by calebkiage** [comment]
This has been implemented as part of the environment login story. @CarolKigoonya can confirm the experience and decide if it's satisfactory.
