### ISSUE TITLE
Support environment login

### ISSUE THREAD

**Issue by calebkiage** [microsoftgraph/msgraph-cli#162]
Using Azure Identity's [EnvironmentCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.environmentcredential?view=azure-dotnet) class would be an easy way to support logging in via environment variables, but it implicitly enables username and password login which the CLI should not support. Because of this, we will have to build our own implementation.

**Comment by CarolKigoonya** [comment]
@darrelmiller please advise on the feasibility of the username & password implementation

**Comment by darrelmiller** [comment]
We MUST NOT implement username & password security.
I'm fine if we want to pick up certain security parameters such as clientId, tenantId and clientSecret from the environment.
