### ISSUE TITLE
Distribution the CLI SDK on the .NET tool

### ISSUE THREAD

**Issue by CarolKigoonya** [microsoftgraph/msgraph-cli#174]

**Comment by ddyett** [comment]
@CarolKigoonya @calebkiage can you draft a plan for how we should distribute the tool, .NET tool or otherwise?

**Comment by calebkiage** [comment]
The CLI is up on NuGet [Microsoft.Graph.Cli](https://www.nuget.org/packages/Microsoft.Graph.Cli)
