### ISSUE TITLE
Improve customer UX for indexer paths using item sub-command

### ISSUE THREAD

**Issue by CarolKigoonya** [microsoftgraph/msgraph-cli#205]
Explore how we can remove the item subcommand to access indexer paths, e.g., GET /users/{user-id} currently uses mgc users item get <id>.

Different scenarios to handle are:
1. without subcommands -> mgc users get <id>
2. with additional subcommands -> mgc users tasks get

**Comment by calebkiage** [comment]
We need to have a way to gracefully handle potential conflicts in the generated code. e.g.
`GET /tests/results` maps to `mgc tests results list`
`GET /tests/{id}/results` maps to `mgc tests item results list --id <id>`

If we remove the `item` sub-command, both of the URL requests will map to the same command with the only difference being the --id parameter.

**Comment by ddyett** [comment]
change is under review
