### ISSUE TITLE
Code snippets availability on GE - add supported language

### ISSUE THREAD

**Issue by CarolKigoonya** [microsoftgraph/msgraph-cli#221]

**Comment by calebkiage** [comment]
Dependent on Raptor validation work

**Comment by timayabi2020** [comment]
Linked PR https://github.com/microsoftgraph/microsoft-graph-explorer-v4/pull/2698

**Comment by peombwa** [comment]
Fixed by https://github.com/microsoftgraph/microsoft-graph-explorer-v4/pull/2698.
