### ISSUE TITLE
Reference documentation on the CLI via documentation links

### ISSUE THREAD

**Issue by CarolKigoonya** [microsoftgraph/msgraph-cli#233]
Linked to microsoft/kiota#2042

Add documentation links when customers use the mgc help command, similar to what PowerShell does (see attachment)

![Image](https://user-images.githubusercontent.com/9033456/214649364-a0e5d48f-2a42-4cef-bc40-c6579a4d29b6.png)

**Comment by calebkiage** [comment]
Waiting on: https://github.com/microsoft/kiota/pull/2251
