### ISSUE TITLE
Create better input convention for handling endpoints that accept JSON data

### ISSUE THREAD

**Issue by calebkiage** [microsoftgraph/msgraph-cli#24]
Currently endpoints that accept JSON data are expressed as commands with a `--body` argument that expects valid JSON data from the user. Explore a better experience e.g. PowerShell takes multiple arguments for the properties of the object

**Comment by ddyett** [comment]
@CarolKigoonya would this be post GA?

**Comment by CarolKigoonya** [comment]
Yes @ddyett his should be post GA.
