### ISSUE TITLE
CLI cannot login on WSL/Ubuntu

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/msgraph-cli#248]
I've installed preview 7 on my Ubuntu distro running in WSL. The login command gives an error:

```bash
DeviceCodeCredential authentication failed: Persistence check failed. Inspect inner exception for details
```

## Environment details

```powershell
wsl --list --verbose
  NAME      STATE           VERSION
* Ubuntu    Running         2
```

```bash
$ cat /etc/issue
Ubuntu 20.04.5 LTS \n \l

$ which mgc
/usr/local/msgraph-cli/mgc

$ mgc --version
0.1.0-preview.7
```

**Comment by calebkiage** [comment]
Hello @jasonjoh,
Thanks for testing out the CLI. On Linux clients, the CLI has a dependency on gnome-keyring for encrypting the access tokens. Could you try the following and let me know if it works for you?

```
sudo apt install gnome-keyring libsecret-1-0

sudo setcap cap_ipc_lock=+ep $(which gnome-keyring-daemon)

export DBUS_SESSION_BUS_ADDRESS=$(dbus-daemon --session --fork --print-address)

export KEYRING_PASSWORD=any-password

dbus-run-session -- echo "$KEYRING_PASSWORD" | gnome-keyring-daemon --daemonize --components=secrets --unlock

mgc login
```

This is what we do for the docker image (translated to use Ubuntu's packages)

**Comment by jasonjoh** [comment]
Thanks @calebkiage that did the trick. Are there plans to simplify this process for end users? At the very least we'll need to document this requirement and explain what these commands do.

**Comment by calebkiage** [comment]
Hey Jason. Yes. These requirements are inherited from the Azure Identity which inherited them from the underlying MSAL library. I think they're mentioned in the Docker [ReadMe](https://github.com/microsoftgraph/msgraph-cli/blob/chore/nrt-code-generation/docker/README.md) file.

**Comment by sebastienlevert** [comment]
I'm getting this after running the script

> DeviceCodeCredential authentication failed: Persistence check failed. Data was written but it could not be read. Possible cause: on Linux, LibSecret is installed but D-Bus isn't running because it cannot be started over SSH.

**Comment by ntsim** [comment]
Have ran the script and seeing the same as @sebastienlevert when trying to `mgc login`. It hangs for a bit before exiting with the same error.

**Comment by CarolKigoonya** [comment]
Hi @ntsim , which environment are you using? Could you share the steps you took to get to this error?

**Comment by ntsim** [comment]
@CarolKigoonya I'm using Ubuntu 22.04.1

**Comment by calebkiage** [comment]
@ntsim, you need to run the following commands whenever you start your shell:

```sh
export DBUS_SESSION_BUS_ADDRESS=$(dbus-daemon --session --fork --print-address)

export KEYRING_PASSWORD=any-password

dbus-run-session -- echo "$KEYRING_PASSWORD" | gnome-keyring-daemon --daemonize --components=secrets --unlock
```

If you want the changes to persist, you'll need to add the commands to your `~/.bashrc` file.

**Comment by ntsim** [comment]
@calebkiage, as mentioned in my original comment, I've previously ran those above commands and was seeing hanging followed by the error posted by @sebastienlevert upon trying to log in.

> DeviceCodeCredential authentication failed: Persistence check failed. Data was written but it could not be read. Possible cause: on Linux, LibSecret is installed but D-Bus isn't running because it cannot be started over SSH.

I've ran the commands as you've posted verbatim, and still seeing the hanging followed by the error.

**Comment by sebastienlevert** [comment]
I'm also still having the same issues today. I think we'd need to look at a clear guide for WSL and ensure this works. It might not be only for WSL but for any "non-GUI" distro of Linux actually.

**Comment by calebkiage** [comment]
@ntsim, @sebastienlevert thanks for confirming. I've been trying to investigate your issue, but I can't reproduce it on WSL. I've tried it on both Ubuntu 20.04 and Ubuntu 22.04.
Could you help me by confirming that DBus is actually running? I suspect maybe the dbus session may have failed to start.
Try running the command `ps -aux`.
You should get a table with running processes on your instance. Check that both dbus and gnome keyring are running as below:
![image](https://user-images.githubusercontent.com/747955/224665000-2d14b7c5-1174-486b-a9ec-a6d3d2dccfe9.png)

**Comment by maisarissi** [comment]
I asked a few folks to test and 4 of 4 had the same issue described by @sebastienlevert . 3 of them installed the WSL just to test our scenario, so no other weird configs applied.

One of the hypotheses brought by Marcelo was that this issue could be related to dbus. Marcelo shared he had an issue with dbus when trying to use the same SSH key between WSL and Windows.

More info they shared with me about version and their machine are below. We might find something that could indicate the error.

The 4 of them were using the same WSL/Ubuntu version:

### Ubuntu
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

### WSL
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770

### Marcelo info
Windows:
Edition    Windows 11 Enterprise
OS build    22621.1848
Experience    Windows Feature Experience Pack 1000.22642.1000.0
Processor    11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz   3.00 GHz

### Carolina info
Windows:
Windows 11 Enterprise
OS build: 22621.1848
Windows Feature Experience Pack 1000.22642.1000.0
Processor: Intel(R) Xeon(R) W-2245 CPU @ 3.90GHz 3.91GHz

### Hallef info
Windows: 
OS Name    Microsoft Windows 11 Enterprise
Version    10.0.22621 Build 22621
Processor    11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, 1805 Mhz, 4 Core(s), 8 Logical Processor(s)

**Comment by calebkiage** [comment]
I have updated the instructions for linux on PR #303. The new component added is systemd that manages system services on linux. It is supported on recent WSL versions which the testers seem to have already.

@sebastienlevert, could you try the new setup?
@maisarissi, if you could have your friends try it out too. Thanks.

You might need to clear the keyring using the command below if you'd run the previous commands.

```
rm -r ~/.local/share/keyrings
```

**Comment by nazarewk** [comment]
In case somebody stumbled upon this issue:
1. I was missing a `libsecret` dependency (which I learned after adding `--debug` to `mgc login`)
2. I am successfully running it with `KeePassXC` secret service implementation without issues https://github.com/microsoftgraph/msgraph-cli/issues/76#issuecomment-2131313824

**Comment by calebkiage** [comment]
Hello @nazarewk, thanks for adding this information for other users. Was the readme useful in your scenario? We tried to document the installation process for all OSes there.

**Comment by nazarewk** [comment]
> Hello @nazarewk, thanks for adding this information for other users. Was the readme useful in your scenario? We tried to document the installation process for all OSes there.

For a bit of context:
- I program in and or worked with packaging multiple programming languages (Python, Go, Java, Lua etc.)
- I have never developed in C/C++/C# or .NET before (I did follow compilation instructions sometimes)
- I didn't work on Windows for over decade and even boot it for ~5 years,
- I have found useful enough packaging (aka build from source) instructions at https://nixos.wiki/wiki/DotNET

What are my feelings about this issue:
1. neither README nor the default message (same as the first post) did not give me any idea on what is wrong (other than failure to persist *something*) or how to proceed/debug further:
  - I suspected it to be something with lack of `gnome-keyring`, but was not sure and was quite certain gnome-keyring only implementation would be hard to achieve and should work with my KeePassXC
2. i dug through internet for 1-2 hours without much success (other than finding the #76)
3. only by chance, as a last resort, I thought of inspecting the `mgc` CLI on what options are available to find `--debug` that gave me better idea on what is wrong
4. I might be wrong, but I felt like all other instances of missing SO/DLLs I have encountered so far were immediately obvious due to a generic "XXX.so not found" type of message, which is completely lacking in this instance.

**Comment by calebkiage** [comment]
Thanks for the added information @nazarewk. It's unfortunate that you found it difficult to set up the CLI. It seems like we need to have a troubleshooting section for users who are on different distributions. We could also improve the error messages to include resolution steps. I appreciate you taking the time to let us know about your experience here. I hope your experience going forward is smoother, but if not, please don't hesitate to let us know.
