### ISSUE TITLE
Cannot authenticate with ClientCertificate strategy on Windows 11

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/msgraph-cli#249]
Preview 7 running in PowerShell 7.3.1 (also happens in Command Prompt)

```powershell
> mgc login --client-id APP_ID --tenant-id TENANT_ID --certificate-name "CN=Microsoft Graph CLI App-Only" --strategy ClientCertificate
```

This command completes without error. Subsequent attempts to call APIs:

```powershell
> mgc users list
Token acquisition failed. Run mgc login command first to get an access token.
```

The certificate and app registration are both valid, as I can use them with the PowerShell SDK to login and list users.

![Screenshot 2023-02-01 133100](https://user-images.githubusercontent.com/8966342/216131992-bb132ca3-85af-4316-a91b-6fa7ccc3f1e3.png)

**Comment by calebkiage** [comment]
Hey @jasonjoh,
Thanks for raising this issue. Could you add the `--debug` flag to your command and share the output you get?
`mgc users list --debug`

**Comment by jasonjoh** [comment]
Unfortunately nothing extra is output.

**Comment by calebkiage** [comment]
Hi @jasonjoh,

We've been working on improving the error output from the CLI this week. This should help troubleshoot the issue you're having.
In the mean time, can you check that the certificate you're providing for the CLI has a private key available in the key store?

**Comment by calebkiage** [comment]
I believe this is solved in the latest version.
