### ISSUE TITLE
Is sending emails via Graph supported?

### ISSUE THREAD

**Issue by bakoontz2** [microsoftgraph/msgraph-cli#277]
Does this SDK support sending of emails via Microsoft Graph?  I don't see anything in the ```mgc -h``` listing, so I'm a bit confused here.  The use case here is to be able to send emails from a Linux container in AKS.

**Comment by calebkiage** [comment]
Hello @bakoontz2, mails should be under users. Try `mgc users item messages -h`

**Comment by bakoontz2** [comment]
@calebkiage Perfect, thank you!
