### ISSUE TITLE
Singularize indexer commands

### ISSUE THREAD

**Issue by calebkiage** [microsoftgraph/msgraph-cli#280]
The new command structure merges the commands in a path with those in a path with id. For example, `/users` and `/users/{user-id}` both have their commands under `mgc users ...`. The proposal is to update the code generator to split them and have `/users/{user-id}` in a new singularized command i.e. `mgc user`.

**Comment by ddyett** [comment]
@CarolKigoonya for call on what/if we should do this.

**Comment by ddyett** [comment]
decision by the team was not to do this work as the naming would be confusing.
