### ISSUE TITLE
Request Headers Support?

### ISSUE THREAD

**Issue by ceuk** [microsoftgraph/msgraph-cli#306]
Hi, from the looks of #86 there has been some work to support a `--headers` option, but I don't seem to be able to set the [`Prefer` header](https://learn.microsoft.com/en-us/graph/api/calendar-list-calendarview?view=graph-rest-1.0&tabs=http#request-headers) for setting calendar view timezones and can't find any documentation on the subject

e.g.

```
mgc users calendar calendar-view list --user-id 1234 --output JSON --start-date-time $(date --iso-8601=seconds) --end-date-time $(date --iso-8601=seconds -d '+1 week') --headers "Prefer=outlook.timezone=\"Africa/Cairo\""
```

I've tried a dozen or so different variants in terms of formatting the --headers option but no luck

Is this implemented/supported?

**Comment by ddyett** [comment]
we don't currently support customer headers but are evaluating.

**Comment by calebkiage** [comment]
Hello @ceuk, thank you for bringing the issue to our attention. As you may have figured out, we don't support that yet. We only show headers that are available in the OpenAPI metadata. As @ddyett mentioned above, we're looking into the possibilities to allow other arbitrary headers. We'll update the issue once work begins on it.

**Comment by CarolKigoonya** [comment]
We had a discussion to allow --header to support this requirement

**Comment by calebkiage** [comment]
Fixed in [preview 2](https://github.com/microsoftgraph/msgraph-cli/releases/tag/v1.0.0-preview.2) release.
