### ISSUE TITLE
Flag to remove odata.context in response

### ISSUE THREAD

**Issue by JasonRatcliffe** [microsoftgraph/msgraph-cli#331]
Any command that is run utilizing `mgz` on a mac, the output always contains `@odata.context` within the json response.  

Below is an example

```
mgc organization list --select "DisplayName, City, State, Country, PostalCode, BusinessPhones"

{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#organization(displayName,city,state,country,postalCode,businessPhones)",
  "value": [
    {
      "displayName": "My Test Tenant",
      "city": "Beverly HIlls",
      "state": "CA",
      "country": null,
      "postalCode": "12345-0001",
      "businessPhones": [
        "1123 5551234"
      ]
    }
  ]
}
```

I have also tried doing the following with the same results.  
```
mgc organization list --select "DisplayName, City, State, Country, PostalCode, BusinessPhones" --headers odata.metadata=full

{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#organization(displayName,city,state,country,postalCode,businessPhones)",
  "value": [
    {
      "displayName": "My Test Tenant",
      "city": "Beverly HIlls",
      "state": "CA",
      "country": null,
      "postalCode": "12345-0001",
      "businessPhones": [
        "1123 5551234"
      ]
    }
  ]
}
```

The docs don't really provide any information on how to get this removed

**Comment by calebkiage** [comment]
Hello, thank you for raising this issue. The MSGraph API is built on [OData](https://www.odata.org/) and `@odata.context` is a standard part of response objects.

You can use the CLI's [JMESPath](https://jmespath.org/) support to perform transformations on the response from the server. JMESPath queries are provided by the `--query` option.

To get only the values array from the response, you can run:

```
mgc organization list --select "DisplayName, City, State, Country, PostalCode, BusinessPhones" --query values
```

Let me know if you need any further assistance.

**Comment by JasonRatcliffe** [comment]
Understood, thank you @calebkiage .  This will get me going for now.  I appreciate the quick response and help.
