### ISSUE TITLE
Wrong encoding when piping/redirecting in shell

### ISSUE THREAD

**Issue by nixx** [microsoftgraph/msgraph-cli#341]
When piping to a terminal i Mac, I get what looks like UTF-16 encoding. 

```shell
`$ mgc service-principals list > out.json
 $ hexdump out.json|head
0000000 007b 000a 0020 0020 0022 0040 006f 0064
0000010 0061 0074 0061 002e 0063 006f 006e 0074
0000020 0065 0078 0074 0022 003a 0020 000a 0022
0000030 0068 0074 0074 0070 0073 003a 002f 002f
0000040 0067 0072 0061 0070 0068 002e 006d 0069
0000050 0063 0072 006f 0073 006f 0066 0074 002e
0000060 0063 006f 006d 002f 0076 0031 002e 0030
0000070 002f 0024 006d 0065 0074 0061 0064 0061
0000080 0074 0061 0023 0073 0065 0072 0076 0069
0000090 0063 0065 0050 0072 0069 006e 0063 0069
``` 

This breaks jq, even if it displays correctly in iTerm

When running iconv

```shell
$ iconv -f utf-16LE -t utf8 out.json > out2.json
$ hexdump out2.json |head
0000000 0a7b 2020 4022 646f 7461 2e61 6f63 746e
0000010 7865 2274 203a 220a 7468 7074 3a73 2f2f
0000020 7267 7061 2e68 696d 7263 736f 666f 2e74
0000030 6f63 2f6d 3176 302e 242f 656d 6174 6164
0000040 6174 7323 7265 6976 6563 7250 6e69 6963
0000050 6170 736c 2c22 200a 2220 6176 756c 2265
0000060 203a 0a5b 2020 2020 0a7b 2020 2020 2020
0000070 6922 2264 203a 3022 6330 6661 3839 2d65
0000080 6631 3135 342d 3866 2d32 3838 6162 382d
0000090 3438 3462 3834 3463 6131 2231 0a2c 2020
``` 
The file displays correctly in VIM, but still breaks jq due to being unvalid JSON (some long values are broken over several lines)

My shell has the following environment variables (some which I consider irrelevant is removed due to privacy reasons):

```shell
COLORFGBG='7;0'
COLORTERM=truecolor
COMMAND_MODE=unix2003
HOME=<masked>
LC_CTYPE=UTF-8
LC_TERMINAL=iTerm2
LC_TERMINAL_VERSION=3.4.16
LESS=-R
LOGNAME=<masked>
LSCOLORS=Gxfxcxdxbxegedabagacad
LS_COLORS='di=1;36:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43'
LaunchInstanceID=<masked>
PAGER=less
PATH=<masked>
PWD=<masked>
PYTHONIOENCODING=utf-8
SHELL=/bin/zsh
SHLVL=1
TERM=xterm-256color
TERM_PROGRAM=iTerm.app
TERM_PROGRAM_VERSION=3.4.16
TMPDIR=<masked>
USER=<masked>
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
ZSH=<masked>
__CFBundleIdentifier=com.googlecode.iterm2
__CF_USER_TEXT_ENCODING=0x0:0:0
```

Im running on a M1 Mac with MacOS Ventura 13.5.2 (22G91) using iTerm as terminal.

This error makes mgc pretty much unusable for my use cases where I often process output making me fall back to pwsh or az instead.

**Comment by calebkiage** [comment]
Thank you for raising this issue. You're right. The output encoding of the CLI is currently UTF-16. I've opened a PR to change it to UTF-8.

Are you able to build the CLI locally?

**Comment by nixx** [comment]
Im able to build it locally, and the encoding issue seems to be fixed.

However, I still unable to get valid JSON. 

As commented in the bug report:

> The file displays correctly in VIM, but still breaks jq due to being unvalid JSON (some long values are broken over several lines)

Output from "

```javascript
{
  "@odata.context":
"https://graph.microsoft.com/v1.0/$metadata#servicePrincipals",
  "@odata.nextLink":
"https://graph.microsoft.com/v1.0/servicePrincipals?$skiptoken=RFNwdAIAAQAAADVTZ
XJ2aWNlUHJpbmNpcGFsXzRjOWExNGQ3LWI5MzgtNDE2Mi1hZWI3LTNkZTdlMzE5N2YzMTVTZXJ2aWNlU
HJpbmNpcGFsXzRjOWExNGQ3LWI5MzgtNDE2Mi1hZWI3LTNkZTdlMzE5N2YzMQAAAAAAAAAAAAAA",
  "value": [
    {
      "id": "XXX",
      "deletedDateTime": null,
      "accountEnabled": true,
      "alternativeNames": [],
      "appDisplayName": "Dynamics Provision",
      "appDescription": null,
      "appId": "XXX",
      "applicationTemplateId": null,
      "appOwnerOrganizationId": "XXX",
      "appRoleAssignmentRequired": false,
---- omitted for brevity --
``` 

The value of the "skipToken" spans multiple lines, and breaks JSON.

**Comment by calebkiage** [comment]
The CLI doesn't do any line wrapping of the json content. That might be happening in your shell. Could you try using the `--json-no-indent` option and see if it helps?

**Comment by calebkiage** [comment]
Actually, I'm wrong. It seems the wrapping behavior is a feature of AnsiConsole.WriteLine. I'm investigating and should publish a fix soon.

**Comment by calebkiage** [comment]
@nixx, there's a PR open that should solve the wrapping issue. Have you also tried out the CLI's JMESPath support? It might handle some of the work jq does.

**Comment by nixx** [comment]
Seems to work fine now. Thanks. 

JMESPath could work in some use cases, but being able to use jq or another JSON-processing tool is a must-have.
