### ISSUE TITLE
[V1 RC Bug Bash]: Why can't I find the concept of me?

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-cli#349]
I'm trying to get information about my user and since I already know Microsoft Graph, I can't find the me resource.

The docs say it is possible: https://github.com/microsoftgraph/msgraph-cli#check-logged-in-user. Perhaps this is a doc bug and it is intentionally missing.

**Comment by ddyett** [comment]
the me endpoint is removed consistent with what we offer in powershell.  This reduces the size of the exe by removing all of the duplicated paths with user/user-id. We may have a look at whether we can fake the endpoing.

**Comment by ddyett** [comment]
@CarolKigoonya we may need to document something here.

**Comment by baywet** [comment]
we could technically map me to /users/id code path like we do in other languages. This wouldn't increase the binary size but might increase the command build up time.

**Comment by calebkiage** [comment]
There's a new idea to work around the command build up time by only building the commands a user will interact with. That work is going to be a major rework on code gen, but the hope is it will give us some more breathing room.

**Comment by ddyett** [comment]
investigate whether we can use an alias.  or we can try just accepting the parameter as something like "--user-id me", then use middleware to swap the url call

**Comment by CarolKigoonya** [comment]
An additional scenario to achieve the concept of me can be via the userId from the get-logged-in-user command in #381
