### ISSUE TITLE
[V1 RC Bug Bash]: Incremental consent not refreshing token

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-cli#352]
My client is not getting authenticated in the way I expect. You can see the experience below in **image 1**.

**Image 1. Client not authenticated after first successful mgc login 
<img width="1014" alt="image" src="https://github.com/microsoftgraph/msgraph-cli/assets/8527305/e76e94c9-310e-42f4-a575-d03cfd30735b">

1. After **14:14:51** I requested mail.read scopes. I successfully consented using the device code flow, control comes back to the CLI in the terminal.
2. After **14:14:59** I try to run the command and it tell me "Access is denied". I try again, the same. The token hasn't been updated on the client.
3. After **14:16:12** I trigger the login process again. Since I already consented, I don't get that screen. Control returns back to the CLI in the terminal.
4. I try to run the command and it is successful. 

Perhaps the token is not getting added to the cache on incremental consent scenarios.

The user here has never used the CLI before and is likely why I'm finding this. This certainly should be fixed for release. 

Interestingly, I wasn't able to repro with the events API and adding a new scope to support the events resources.

**Comment by ddyett** [comment]
@calebkiage can we look into this one.
