### ISSUE TITLE
[V1 RC Bug Bash]: Linux readme instructions need refinement

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-cli#354]
The Windows and Mac instructions are more refined and are organized more like instructions. The Linux instructions read more like notes. I'm not successfully running the CLI on WSL.

**Comment by ddyett** [comment]
@CarolKigoonya assigning this one to note for release docs if we need to do something more.

**Comment by ddyett** [comment]
updated and merges into branch.
