### ISSUE TITLE
[V1 RC Bug Bash] Can't install CLI as a dotnet tool with .NET 6.0

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/msgraph-cli#356]
.NET 6.0 is an LTS version that is supported till the end of 2024 (https://dotnet.microsoft.com/en-us/download/visual-studio-sdks). However, I can't install the CLI if I am on .NET 6.0.

Is this a deliberate design decision?

### Error:
---
$ dotnet tool install --global Microsoft.Graph.Cli --prerelease

/var/folders/5t/wbzr_z150bv82_n91bjp8jcm0000gn/T/tsordjzj.gtb/restore.csproj : error NU1202: Package Microsoft.Graph.Cli 1.0.0-rc.1 is not compatible with net6.0 (.NETCoreApp,Version=v6.0) / any. Package Microsoft.Graph.Cli 1.0.0-rc.1 supports: net7.0 (.NETCoreApp,Version=v7.0) / any
The tool package could not be restored.
Tool 'microsoft.graph.cli' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

---
OS: MacOS Monterey 12.4

**Comment by ddyett** [comment]
The team has discussed and we will support 7+.  We will update the documentation as well to reflect this.
