### ISSUE TITLE
Error when running ./mgc

### ISSUE THREAD

**Issue by Jonas-Hangvar** [microsoftgraph/msgraph-cli#404]
I get the following when running the Microsoft Graph CLI 1.1.0 GA ./mgc in a terminal (zsh) on a Macbook Pro M3:

Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.Graph.Cli.Program.Main(String[] args)
   at Microsoft.Graph.Cli.Program.<Main>(String[] args)
zsh: abort      ./mgc

**Comment by calebkiage** [comment]
Hello @Jonas-Hangvar, this issue should be fixed in version 1.1.1

Thank you for reporting this.
