### ISSUE TITLE
Running mgc returns "Could not find a part of the path 'Z:\.mgc'."

### ISSUE THREAD

**Issue by OneUser1** [microsoftgraph/msgraph-cli#414]
When trying to login I receive an error: "Could not find a part of the path 'Z:\.mgc'."
![image](https://github.com/microsoftgraph/msgraph-cli/assets/80819060/3d4778aa-619f-43ac-9412-84c334e433d9)

Also, when trying to run the mgc command without any parameter I receive an error (while mgc --help works fine). The behaviour is the same on Windows PowerShell 5.1 and Pwsh 7.4.0.

Am I doing something wrong? I previously added mgc folder path to the PATH environment variable which works fine. Where does the Z: drive come from?

Thanks for your help!

**Comment by calebkiage** [comment]
Hello @OneUser1, what is the value of your `HOME`, `HOMEDRIVE` and `HOMEPATH` environment variables?

**Comment by OneUser1** [comment]
Hi @calebkiage, thanks for your answer! Pls find the output below:
`PS C:\> mgc login --strategy InteractiveBrowser --debug
Could not find a part of the path 'Z:\.mgc'.
PS C:\> $HOME
C:\Users\<username>
PS C:\> $Env:HOME
PS C:\> $Env:HOMEDRIVE
Z:
PS C:\> $Env:HOMEPATH
\
PS C:\>`

Hope this helps. I didn't change anything on purpose. This is the PS 7 default after I installed it for using the mgc CLI tool.

**Comment by calebkiage** [comment]
@OneUser1, the issue is coming from the HOMEDRIVE environment variable.

can you run the following commands:
```shell
$env:HOMEDRIVE="C:"
```

```shell
$env:HOMEPATH="\Users\<username>"
```

Replace `<username>` with your username.

Afterwards, run `mgc`.

If that works, you need to persist the changes to the environment variables.

**Comment by OneUser1** [comment]
Thank you, that solved it. I don't know where the Z: drive comes from.. I will see how I change it permanently. Thanks again!
