### ISSUE TITLE
Unable to pull cli in docker as it is behind auth

### ISSUE THREAD

**Issue by tehho** [microsoftgraph/msgraph-cli#463]
Please open up cli to the world?
Maybe put it on mcr?
failed to resolve reference "docker.io/library/msgraph-cli:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

**Comment by calebkiage** [comment]
Hello @tehho, there's a docker image hosted with docker packages. Use:

```
docker pull ghcr.io/microsoftgraph/msgraph-cli:latest
```
