### ISSUE TITLE
Certificate Thumb print not found on Linux

### ISSUE THREAD

**Issue by sleepless-swan** [microsoftgraph/msgraph-cli#465]
I am using Msgraph Cli on a WSL. Whenever I try to use the certificate thumb print to login I get the error that a valid certificate has not been found in current user's store, even though it is installed and is showing in the certificate list for the current user. I have confirmed the thumb print is valid by running the command in PowerShell. Is there another location I should place the certificate in?

**Comment by calebkiage** [comment]
Hi @sleepless-swan, thanks for raising this issue. To help you better, we need more information about your session.

1. What command are you running on PowerShell to confirm the certificate exists?
2. How/Where have you installed the certificates?
3. What version of the CLI are you using?

The CLI uses the `X509Store` class to read the current user's personal certificates. You can add a new certificate by running the following script in PowerShell:

```powershell
$store = [X509Store]::new('My', 'CurrentUser', 'ReadWrite')
$store.Add([X509Certificate2]::new('path/to/mycert.pfx', '<passphrase>', [X509KeyStorageFlags]::PersistKeySet))
$store.Dispose()
```

**Comment by sleepless-swan** [comment]
1. I'm using `Get-ChildItem Cert:\CurrentUser\My | ft ` and I am able to see the certificate. The certificate login works fine on PowerShell, but not on WSL.
2. I created the certificate using the PowerShell command on my PC and installed it on the same PC. I tried to connect using the certificate thumb print option and it was working fine on said PC. 

on WSL, I used the command  `./mgc login --certificate-thumb-print 'thumb print' --strategy ClientCertificate` but it's giving me the error 
![image_2024-04-24_093748926](https://github.com/microsoftgraph/msgraph-cli/assets/140255208/1f2e745d-430f-45d8-817e-d829f620b1f6)

I noticed in the help menu on WSL that the certificate option looks for certificates in the current user's store: 

![image_2024-04-24_093917312](https://github.com/microsoftgraph/msgraph-cli/assets/140255208/03f3ad95-677f-43f5-bc97-5d1b728ec655)

I can see the certificate using both PowerShell and Windows GUI though.

3. I am using MsGraph version 1.7.0 and the WSL is the latest version.

**Comment by calebkiage** [comment]
Hello @sleepless-swan, do I understand correctly that you installed the certificate on Windows? If so, that won't work from the WSL environment. WSL, though accessible in windows is a separate OS with its own resources. Think of it like a virtual machine within Windows that has some useful integrations. You need to install the certificate in the WSL distribution as well.

**Comment by sleepless-swan** [comment]
What you understood is correct. I do have the certificate stored in the WSL. Is it possible to specify the path in the thumb print argument `./mgc login --certificate-thumb-print 'thumb print' --strategy ClientCertificate` ? I tried that but it did not work for me though.

**Comment by calebkiage** [comment]
@sleepless-swan, we don't have the feature to specify a certificate file location since most certificates require passwords to access and we need to access the certificate whenever we make a request.
What you could do instead is to [install PowerShell in your WSL distribution](https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.4), then use the PowerShell commands in [the comment above](https://github.com/microsoftgraph/msgraph-cli/issues/465#issuecomment-2073660042) to install your certificate.

After that is done, try logging in again.
