### ISSUE TITLE
API approval required

### ISSUE THREAD

**Issue by stefanstranger** [microsoftgraph/msgraph-cli#48]
I wanted to test out the new MSGraph CLI and after running "mgc.exe login --scopes User.Read" I was confronted with an approval screen.

Sorry, but we’re having trouble signing you in.

AADSTS65002: Consent between first party application '04b07795-8ddb-461a-bbee-02f9e1bf7b46' and first party resource '00000003-0000-0000-c000-000000000000' must be configured via preauthorization - applications owned and operated by Microsoft must get approval from the API owner before requesting tokens for that API.

It's in the Microsoft tenant.

Regards,
Stefan [MSFT]

**Comment by calebkiage** [comment]
Hi @stefanstranger, the latest version of the application [v0.1.0-preview.2](https://github.com/microsoftgraph/msgraph-cli/tree/v0.1.0-preview.2) requires that you set the tenant id and client id in the app-settings.json file. The next version should allow you to supply them to the login command. Use a tenant id and client id that is registered to access the graph.microsoft.com API

**Comment by baywet** [comment]
I was able to work this around by doing the following

```shell
rm -r ~\.mgc
mgc.exe login --scopes "User.Read" --client-id "14d82eec-204b-4c2f-b7e8-296a70dab67e" --tenant-id "<my tenant id>"
```

> Note: scopes don't really matter, only provided for reference

> Note: the client id is the one from MS Graph PS

we do have work captured in #80 to fix that but in the meantime you can use that workaround to explore the CLI.
