### ISSUE TITLE
Create a readme with basic instructions on how to install and use the CLI

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-cli#81]

**Comment by sebastienlevert** [comment]
I'd love to chime in here as I have absolutely no clue on how to install the CLI and getting started. Adding @CarolKigoonya to the conversation! Though, I'd looooooove to use it!

**Comment by CarolKigoonya** [comment]
@sebastienlevert working on this to be availed next week. Meanwhile please go to the releases (latest at the top) then assets. https://github.com/microsoftgraph/msgraph-cli/releases
