### ISSUE TITLE
[Tracking] Support Providing Custom Headers

### ISSUE THREAD

**Issue by calebkiage** [microsoftgraph/msgraph-cli#86]
Allow users to provide custom headers that will be passed through to the server. Some endpoints require specific headers to return the correct result. An example is the [users/$count](https://graph.microsoft.com/v1.0/users/$count) endpoint that needs the user to provide `ConsistencyLevel: eventual`.

- Add option to allow a user to provide custom headers (`--headers`)
  - Headers formatting and parsing
  - If the headers are documented in the OpenApi doc as parameters, can we add additional options that map to the headers? for example, some endpoints have `If-Match` and `ConsistencyLevel` documented
![image](https://user-images.githubusercontent.com/747955/161080267-e9770edf-420f-47f5-987f-9a0298aebf8b.png)
Can the CLI add `--if-match` and `--consistency-level` options? This will allow validating specific headers by marking their options as required that will then show the user an error. Yes

- ~~Security~~
  - ~~Can the user provide headers like `Authentication`?~~ No

- #### Documented headers support
  - [x] #98
  - [x] #99
  - [x] #100

**Comment by darrelmiller** [comment]
The objective should not be to allow users to provide custom headers.  We should take the metadata that tells us that the API has custom headers and create a parameter for those headers.

This is how it is done in PowerShell
<img width="934" alt="image" src="https://user-images.githubusercontent.com/447694/161581335-bc7e4fb0-5a8e-4de9-b1e8-7d98c836dbf8.png">

**Comment by calebkiage** [comment]
@darrelmiller, some endpoints don't specify the headers in the metadata. The users/$count endpoint is an example of that. Maybe we need to fix those endpoints?
![image](https://user-images.githubusercontent.com/747955/161582418-f52d7473-1a14-4bb9-855b-a545a9a939ad.png)

**Comment by darrelmiller** [comment]
Currently we add them in out metadata XSLT.
