### ISSUE TITLE
MacOS Installation: Application cannot run due to unverified developer source

### ISSUE THREAD

**Issue by roinochieng** [microsoftgraph/msgraph-cli#93]
When running the OSx exe on the  Preview 3 release, the application installation is inturrupted by the following error:
<img width="251" alt="Screenshot 2022-03-29 at 14 06 57" src="https://user-images.githubusercontent.com/8355669/162201723-2f08e4e9-e123-4f3d-ada9-7393c4596aba.png">

**Comment by carlowahlstedt** [comment]
FWIW, the cli work around here is to use `xattr -r -d com.apple.quarantine "[path-to-application]"`. However, this is obviously not the ideal scenario for a command line application.

**Comment by darrelmiller** [comment]
@calebkiage  Can this be closed now that we are signing the binary?

**Comment by calebkiage** [comment]
@darrelmiller, ok. I'll create another issue to track the signing task.

**Comment by ddyett** [comment]
this issue tracks getting everything working on MacOS, x64 and arm binaries.

**Comment by calebkiage** [comment]
MacOS signing and notarizing should be closed by #241
