### ISSUE TITLE
--output option is listed as Required 

### ISSUE THREAD

**Issue by roinochieng** [microsoftgraph/msgraph-cli#95]
$ ./mgc me get -h shows the --output option in the options list and is listed as required. The command runs fine without --option, we should remove that it's listed as required
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/8355669/162206000-d3faadd9-3d81-4629-92be-b757bcf71a5b.png)
.

**Comment by calebkiage** [comment]
It is actually required, but it defaults to JSON if unspecified.

**Comment by CarolKigoonya** [comment]
Closing this issue because --output is required.
