### ISSUE TITLE
Remove None as an --output option

### ISSUE THREAD

**Issue by roinochieng** [microsoftgraph/msgraph-cli#96]
We have JSON, Table and None options listed as output options:
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/8355669/162206639-ac3563b9-f998-4951-998c-531335b82f7f.png)
Is there any relevant use for this?

**Comment by roinochieng** [comment]
Additionally, can we make these options in lower case for consistency? @calebkiage

**Comment by calebkiage** [comment]
They're not case sensitive @roinochieng you can use `table` as well

**Comment by calebkiage** [comment]
Currently, the `none` output option hasn't been implemented, but we could use that as a no-op option that doesn't output anything. This would be similar to some CLI tools' `--quiet` option.

**Comment by calebkiage** [comment]
microsoft/kiota#1794 implements the output option. This is in line with [Azure CLI's `none`](https://docs.microsoft.com/en-us/cli/azure/format-output-azure-cli) option
